repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/zmoon/findent-pre-commit
    rev: "65627b8"
    hooks:
      # NOTE: doesn't work on Windows currently
      - id: findent-pypi
        args: ['-i3']
        exclude: |
            (?x)^(
                src/core/charpak_mod\.F90|
                src/core/qfyaml_mod\.F90|
                src/process/old/.*\.F90|
                drivers/ccpp/.*\.F90|
                parameters/.*\.F90
            )$

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [PyYAML]
      - id: cmake-lint
        additional_dependencies: [PyYAML]
