### catchem_config.yml: CATChem Runtime configuration options.
### Customized for simulations using the aerosols-only mechanism.
###
### NOTE: Add quotes around nitrogen oxide ('NO'), because YAML
### parsers will confuse this with a negative "no" value.

#============================================================================
# Simulation settings
#============================================================================
simulation:
  name: aerosol
  start_date: 20240501 0000
  end_date: 20240501 0100
  root_data_dir: ./data
  met_field: ufs
  species_database_file: ./species_database.yml
  species_metadata_output_file: ./species_metadata.yml
  verbose:
    activate: false
    on_cores: root       # Allowed values: root all

#============================================================================
# Grid settings
#============================================================================
grid:
  resolution: 4.0x5.0
  number_of_levels: 28 
  longitude:
    range: -180 180 
    center_at_180: 
  latitude:
    range: -90 90
    half_size_polar_boxes: 


#============================================================================
# Settings for CATChem operations
#============================================================================
operations:

  chemistry:
    activate: false

  convection:
    activate: false

  dry_deposition:
    activate: false
    diag_alt_above_sfc_in_m: 10

  pbl_mixing:
     activate: false
     use_non_local_pbl: false

  photolysis:
    activate: false

  transport:
    transported_species:
      - DST1
      - DST2
      - DST3
      - DST4
      - SALA
      - SALC

  wet_deposition:
    activate: false

#============================================================================
# Settings for CATChem aerosols
#============================================================================
aerosols:

  dust:
    activate: true

  sea_salt:
    activate: true




