name: CI

on:
  push:
    branches: [main, feature/catchem_begins]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [gfortran-10, gfortran-11, gfortran-12, ifort]
    defaults:
      run:
        shell: bash -l {0}
    env:
      BUILD_DIR: build

    steps:
      - uses: actions/checkout@v4

      - name: Get Intel compilers with APT
        if: ${{ matrix.compiler == 'ifort' }}
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: intel-classic
          version: "2021.9"  # oneAPI 2023.1.0

      - name: Build
        run: |
          cmake -B $BUILD_DIR
          cmake --build $BUILD_DIR
        env:
          FC: ${{ matrix.compiler }}

      - name: Test
        run: ctest --test-dir ${BUILD_DIR}/tests
